### ISSUE TITLE
Reorganize and enhance user-facing help and guides

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/commons#257]
- [x] Re-theme the help and support site and consolidate into one help site from multiple
- [x] Enable comments on FAQ/Guides
- [x] Add Ninja Forms for asking questions and tech support
