### ISSUE TITLE
WordPress 5.7 Update

### ISSUE THREAD

**Issue by mikethicke** [MESH-Research/commons#62]
- [x] Update on msudev
- [x] Fix any major issues
- [x] Update on hcdev
- [x] Testing
- [x] Address any issues found in testing
- [x] Push fixes to prod
- [x] Update WP on prod
